const en = {
    'nav.services': 'Services',
    'nav.projects': 'Success stories',
    'nav.diffusion': 'Diffusions',
    'nav.team': 'Team',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact Us',
    'nav.partners': 'Partners',
    'nav.pricing': 'Pricings',
    'nav.about': 'About Us',
    "callToAction.hero": "Start the Adventure",
    "home.services.title": "Our services",
    "home.services.description": "Comprehensive solutions for your business success in the DRC",

    "about.banner.title": "Together, let's build the future of Congolese entrepreneurship",
    "about.banner.description": "Meet'eka supports Congolese entrepreneurs in their development, from the informal to sustainable success.",

    "about.stats.580k+": "Listed companies in DRC",
    "about.stats.95%": "Companies in the Informal sector",
    "about.stats.43%": "Women-owned businesses",
    "about.stats.80%": "SMEs with Financing Difficulties",

    "about.challenges.title": "The challenges",
    "about.challenges.coins.title": "Limited access to financing",
    "about.challenges.coins.description": "According to the Central Bank of Congo, some 80% of small businesses are experiencing difficulties in financing and expansion.",
    "about.challenges.BookOpen.title": "Lack of awareness",
    "about.challenges.BookOpen.description": "Many entrepreneurs are unaware of the benefits of formalization, or lack knowledge of the procedures involved.",
    "about.challenges.FileText.title": "Administrative complexity",
    "about.challenges.FileText.description": "The steps involved in formalizing a company are often perceived as complex, time-consuming and costly.",
    "about.challenges.Calculator.title": "Cumbersome tax system",
    "about.challenges.Calculator.description": "Taxation is deemed excessive, pushing entrepreneurs into the informal sector.",

    "services.simplification-administrative.slug": "administrative-simplification",
    "services.callToAction": "Read more",
    "services.simplification-administrative.title": "Administrative simplification",
    "services.simplification-administrative.description": "We take the administrative work out of your hands, so you can concentrate on your core business.",
    "services.simplification-administrative.accompagnement-dans-les-procédures-légales": "Assistance with legal procedures",
    "services.simplification-administrative.optimisation-des-processus-administratifs": "Optimizing administrative processes",
    "services.simplification-administrative.gestion-documentaire-simplifiée": "Simplified document management",


    "services.information-fiscale.slug": "tax-information",
    "services.information-fiscale.title": "Tax information",
    "services.information-fiscale.description": "Access all the essential information on taxation and incentives available in the DRC.",
    "services.information-fiscale.veille-fiscale-personnalisée": "Customized tax watch",
    "services.information-fiscale.guide-des-incitations-fiscales": "Guide to tax incentives",
    "services.information-fiscale.conseil-en-optimisation-fiscale": "Tax optimization consulting",

    "services.acces-financements.slug": "acces-financements",
    "services.acces-financements.title": "Access to Financing",
    "services.acces-financements.description": "We can help you find and secure financing tailored to your needs.",
    "services.acces-financements.mise-en-relation-avec-les-investisseurs": "Putting you in touch with investors",
    "services.acces-financements.préparation-des-dossiers-de-financement": "Preparing financing files",
    "services.acces-financements.négociation-des-conditions": "Negotiating terms and conditions",

    "services.formation-continue.slug": "continuing-education",
    "services.formation-continue.title": "Continuing Education",
    "services.formation-continue.description": "Develop your team's skills with our customized training programs.",
    "services.formation-continue.formations-managériales": "Management training",
    "services.formation-continue.ateliers-pratiques": "Practical workshops",
    "services.formation-continue.coaching-personnalisé": "Personalized coaching",

    "services.accompagnement-strategique.slug": "strategic-support",
    "services.accompagnement-strategique.title": "Strategic Support",
    "services.accompagnement-strategique.description": `Benefit from personalized support to optimize your growth and development.`,
    "services.accompagnement-strategique.analyse-de-marché": "Market analysis",
    "services.accompagnement-strategique.planification-stratégique": "Strategic planning",
    "services.accompagnement-strategique.suivi-des-performances": "Performance monitoring",

    "services.stabilite-securite.slug": "stability-security",
    "services.stabilite-securite.title": "Stability & Safety",
    "services.stabilite-securite.description": `We help you to navigate the Congolese business environment safely.`,
    "services.stabilite-securite.gestion-des-risques": "Risk management",
    "services.stabilite-securite.conformité-réglementaire": "Regulatory compliance",
    "services.stabilite-securite.protection-des-intérêts": "Protection of interests",

    "success-stories.title": "Success Stories",
    "success-stories.description": "Celebrating the achievements of Congolese entrepreneurs",
    "success-stories.more": "Read Success Story",

    "diffusions.title": "Latest broadcasts",
    "diffusions.description": "Expert advice and strategies for your digital success",
    "diffusions.more": "See all broadcasts",

    "teams.title": "Our team",
    "teams.description": "The experts behind your digital success",

    "customers.title": "Customer Reviews",
    "customers.description": "What our clients say about working with us",

    "contact.title": "Let's Talk",
    "contact.description": "Ready to start your digital journey? Get in touch with us today.",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.name": "Name",
    "contact.name.placeholder": "John Doe",
    "contact.message": "Message",
    "contact.message.placeholder": "Tell us about your project...",
    "contact.button.send": "Send Message",

    "footer.description": "Your trusted partner for digital marketing excellence.",
    "footer.right": "All rights reserved.",
    "footer.section.follow": "Follow Us",
    "footer.section.contact": "Contact",
    "footer.section.links": "Quick Links",
    "footer.section.links.services": "Services",
    "footer.section.links.success-stories": "Success stories",
    "footer.section.links.diffusions": "Broadcasts",
    "footer.section.links.partenaires": "partners"
}
export default en