const en = {
    'nav.services': 'Services',
    'nav.projects': 'Success stories',
    'nav.diffusion': 'Broadcasts',
    'nav.blog': 'Blogs',
    'nav.team': 'Team',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact Us',
    'nav.entreprises': 'Entreprises',
    'nav.fiscalities': 'Fiscalités',
    'nav.organisations': 'Organisations',
    'nav.missions': 'Missions',
    'nav.events': 'Events',
    'nav.pricing': 'Pricings',
    'nav.about': 'About Us',
    "callToAction.hero": "Start the Adventure",
    "home.services.title": "Our services",
    "home.services.description": "Comprehensive solutions for your business success in the DRC",

    "about.banner.title": "Together, let's build the future of Congolese entrepreneurship",
    "about.banner.description": "Meeteka supports Congolese entrepreneurs in their development, from the informal to sustainable success.",

    "about.stats.580k+": "Listed companies in DRC",
    "about.stats.95%": "Companies in the Informal sector",
    "about.stats.43%": "Women-owned businesses",
    "about.stats.80%": "SMEs with Financing Difficulties",

    "about.challenges.title": "The challenges",
    "about.challenges.coins.title": "Limited access to financing",
    "about.challenges.coins.description": "According to the Central Bank of Congo, some 80% of small businesses are experiencing difficulties in financing and expansion.",
    "about.challenges.BookOpen.title": "Lack of awareness",
    "about.challenges.BookOpen.description": "Many entrepreneurs are unaware of the benefits of formalization, or lack knowledge of the procedures involved.",
    "about.challenges.FileText.title": "Administrative complexity",
    "about.challenges.FileText.description": "The steps involved in formalizing a company are often perceived as complex, time-consuming and costly.",
    "about.challenges.Calculator.title": "Cumbersome tax system",
    "about.challenges.Calculator.description": "Taxation is deemed excessive, pushing entrepreneurs into the informal sector.",

    "about.solutions.title": "The Solutions",
    "about.solutions.administrative.title": "Administrative simplification",
    "about.solutions.administrative.description": "Simplified guides, interactive checklists and personalized support for formalization.",
    "about.solutions.administrative.label": "Reduced formalization time",
    "about.solutions.fiscale.title": "Tax information",
    "about.solutions.fiscale.description": "Clear, up-to-date information on taxation and opportunities for SMEs.",
    "about.solutions.fiscale.label": "Reduce search time",
    "about.solutions.financements.title": "Access to Financing",
    "about.solutions.financements.description": "Connection with financial institutions and microfinance programs.",
    "about.solutions.financements.label": "Improved eligibility rate",
    "about.solutions.formation.title": "Continuing Education",
    "about.solutions.formation.description": "Online training modules on marketing, accounting and business management.",
    "about.solutions.formation.label": "Training completion rate",

    "about.callToAction.title": "Ready to Transform Your Business?",
    "about.callToAction.description": "Join the Congolese entrepreneurs who trust Meeteka for their growth and digital transformation.",
    "about.callToAction.button.label": "Start Now",

    "services.simplification-administrative.slug": "administrative-simplification",
    "services.callToAction": "Read more",
    "services.simplification-administrative.title": "Administrative simplification",
    "services.simplification-administrative.description": "We take the administrative work out of your hands, so you can concentrate on your core business.",
    "services.simplification-administrative.accompagnement-dans-les-procédures-légales": "Assistance with legal procedures",
    "services.simplification-administrative.optimisation-des-processus-administratifs": "Optimizing administrative processes",
    "services.simplification-administrative.gestion-documentaire-simplifiée": "Simplified document management",


    "services.information-fiscale.slug": "tax-information",
    "services.information-fiscale.title": "Tax information",
    "services.information-fiscale.description": "Access all the essential information on taxation and incentives available in the DRC.",
    "services.information-fiscale.veille-fiscale-personnalisée": "Customized tax watch",
    "services.information-fiscale.guide-des-incitations-fiscales": "Guide to tax incentives",
    "services.information-fiscale.conseil-en-optimisation-fiscale": "Tax optimization consulting",

    "services.acces-financements.slug": "acces-financements",
    "services.acces-financements.title": "Access to Financing",
    "services.acces-financements.description": "We can help you find and secure financing tailored to your needs.",
    "services.acces-financements.mise-en-relation-avec-les-investisseurs": "Putting you in touch with investors",
    "services.acces-financements.préparation-des-dossiers-de-financement": "Preparing financing files",
    "services.acces-financements.négociation-des-conditions": "Negotiating terms and conditions",

    "services.formation-continue.slug": "continuing-education",
    "services.formation-continue.title": "Continuing Education",
    "services.formation-continue.description": "Develop your team's skills with our customized training programs.",
    "services.formation-continue.formations-managériales": "Management training",
    "services.formation-continue.ateliers-pratiques": "Practical workshops",
    "services.formation-continue.coaching-personnalisé": "Personalized coaching",

    "services.accompagnement-strategique.slug": "strategic-support",
    "services.accompagnement-strategique.title": "Strategic Support",
    "services.accompagnement-strategique.description": `Benefit from personalized support to optimize your growth and development.`,
    "services.accompagnement-strategique.analyse-de-marché": "Market analysis",
    "services.accompagnement-strategique.planification-stratégique": "Strategic planning",
    "services.accompagnement-strategique.suivi-des-performances": "Performance monitoring",

    "services.stabilite-securite.slug": "stability-security",
    "services.stabilite-securite.title": "Stability & Safety",
    "services.stabilite-securite.description": `We help you to navigate the Congolese business environment safely.`,
    "services.stabilite-securite.gestion-des-risques": "Risk management",
    "services.stabilite-securite.conformité-réglementaire": "Regulatory compliance",
    "services.stabilite-securite.protection-des-intérêts": "Protection of interests",

    "success-stories.title": "Success Stories",
    "success-stories.description": "Celebrating the achievements of Congolese entrepreneurs",
    "success-stories.more": "Read Success Story",

    "success-stories.banner.title": "Our Success stories",
    "success-stories.banner.description": "Find out how we've helped Congolese companies achieve their goals and turn their ambitions into success.",
    "success-stories.button.more": "See details",

    "partners.banner.title": "Our partners",
    "partners.banner.description": "Discover our network of experts and professionals dedicated to your success.",
    "partners.button.more": "See details",

    "pricings.banner.title": "Our prices",
    "pricings.banner.description": "Solutions for every stage of your growth. Choose the plan that best suits your needs.",
    "pricings.callToAction.title": "Got any questions?",
    "pricings.callToAction.description": "Our team is here to help you choose the best solution.",
    "pricings.callToAction.button.label": "Contact us",

    "diffusions.title": "Latest broadcasts",
    "diffusions.description": "Expert advice and strategies for your digital success",
    "diffusions.more": "See all broadcasts",
    "diffusions.banner.title": "Our Broadcasts",
    "diffusions.banner.description": "Discover our guides and resources for developing your business and succeeding in the digital economy.",

    "fiscalities.title": "Dernières Fiscalités",
    "fiscalities.description": "Découvrez nos appels d'offres en cours, explorez de nouvelles missions passionnantes et trouvez des opportunités de financement pour vos projets. Toutes les informations clés pour collaborer et développer vos activités sont ici.",
    "fiscalities.more": "Voir toutes les fiscalités",
    "fiscalities.banner.title": "Nos Fiscalités",
    "fiscalities.banner.description": "Explorez nos fiscalités pour des analyses approfondies, des guides pratiques et des réflexions inspirantes qui vous aideront à réussir vos projets, mieux comprendre le monde, développer vos compétences.",

    "missions.title": "Latest Missions",
    "missions.description": "Expert advice and strategies for your digital success",
    "missions.more": "See all Missions",
    "missions.banner.title": "Our Missions",
    "missions.banner.description": "Discover our guides and resources for developing your business and succeeding in the digital economy.",

    "blogs.title": "Dernièrs Blogs",
    "blogs.description": "Conseils d'experts et stratégies pour votre succès digital",
    "blogs.more": "Voir tout les blogs",
    "blogs.banner.title": "Nos Blogs",
    "blogs.banner.description": "Découvrez nos guides et ressources pour développer votre entreprise et réussir dans l'économie digitale.",

    "events.banner.title": "Our Events",
    "events.banner.description": "Découvrez notre réseau d'experts et de professionnels dédiés à votre réussite.",
    "events.button.more": "See details",

    "teams.title": "Our team",
    "teams.description": "The experts behind your digital success",

    "customers.title": "Customer Reviews",
    "customers.description": "What our clients say about working with us",

    "contact.title": "Let's Talk",
    "contact.description": "Ready to start your digital journey? Get in touch with us today.",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.name": "Name",
    "contact.name.placeholder": "John Doe",
    "contact.message": "Message",
    "contact.message.placeholder": "Tell us about your project...",
    "contact.button.send": "Send Message",

    "footer.description": "Your trusted partner for digital marketing excellence.",
    "footer.right": "All rights reserved.",
    "footer.section.follow": "Follow Us",
    "footer.section.contact": "Contact",
    "footer.section.links": "Quick Links",
    "footer.section.links.services": "Services",
    "footer.section.links.success-stories": "Success stories",
    "footer.section.links.diffusions": "Broadcasts",
    "footer.section.links.organisations": "Organisations",
    "footer.section.links.missions": "Missions",
    "footer.section.links.blogs": "Blogs",
    "footer.section.links.events": "Evenements",
    "footer.section.links.entreprises": "Entreprises"
}
export default en