const fr = {
    'nav.services': 'Services',
    'nav.projects': 'Histoires à succès',
    'nav.diffusion': 'Diffusions',
    'nav.blog': 'Blogs',
    'nav.team': 'Équipe',
    'nav.reviews': 'Avis',
    'nav.contact': 'Contactez-nous',
    'nav.entreprises': 'Entreprises',
    'nav.organisations': 'Organisations',
    'nav.missions': 'Missions',
    'nav.events': 'Evenements',
    'nav.pricing': 'Prix',
    'nav.about': 'À propos',
    "callToAction.hero": "Commencez l'Aventure",
    "home.services.title": "Nos Services",
    "home.services.description": "Des solutions complètes pour votre réussite entrepreneuriale en RDC",

    "about.banner.title": "Ensemble, Construisons l'Avenir de l'Entrepreneuriat Congolais",
    "about.banner.description": "Meeteka accompagne les entrepreneurs congolais dans leur développement, de l'informel vers le succès durable.",

    "about.stats.580k+": "Entreprises Recensées en RDC",
    "about.stats.95%": "Entreprises dans l'Informel",
    "about.stats.43%": "Entreprises Gérées par des Femmes",
    "about.stats.80%": "PME avec Difficultés de Financement",

    "about.challenges.title": "Les Défis à Relever",
    "about.challenges.coins.title": "Accès limité aux financements",
    "about.challenges.coins.description": "Environ 80% des petites entreprises rencontrent des difficultés de financement et d'expansion selon la Banque Centrale du Congo.",
    "about.challenges.BookOpen.title": "Manque de sensibilisation",
    "about.challenges.BookOpen.description": "De nombreux entrepreneurs ne sont pas informés des avantages de la formalisation ou manquent de connaissances sur les procédures.",
    "about.challenges.FileText.title": "Complexité administrative",
    "about.challenges.FileText.description": "Les démarches pour formaliser une entreprise sont souvent perçues comme complexes, longues et coûteuses.",
    "about.challenges.Calculator.title": "Système fiscal lourd",
    "about.challenges.Calculator.description": "La fiscalité est jugée excessive, poussant les entrepreneurs à rester dans l'informel.",

    "about.solutions.title": "Nos Solutions",
    "about.solutions.administrative.title": "Simplification Administrative",
    "about.solutions.administrative.description": "Guides simplifiés, check-lists interactives et accompagnement personnalisé pour la formalisation.",
    "about.solutions.administrative.label": "Réduction du temps de formalisation",
    "about.solutions.fiscale.title": "Information Fiscale",
    "about.solutions.fiscale.description": "Informations claires et mises à jour sur la fiscalité et les opportunités pour les PME.",
    "about.solutions.fiscale.label": "Réduction du temps de recherche",
    "about.solutions.financements.title": "Accès aux Financements",
    "about.solutions.financements.description": "Connexion avec les institutions financières et programmes de microfinance.",
    "about.solutions.financements.label": "Amélioration du taux déligibilité",
    "about.solutions.formation.title": "Formation Continue",
    "about.solutions.formation.description": "Modules de formation en ligne sur le marketing, la comptabilité et la gestion d'entreprise.",
    "about.solutions.formation.label": "Taux de complétion des formations",


    "about.callToAction.title": "Prêt à Transformer Votre Entreprise ?",
    "about.callToAction.description": " Rejoignez les entrepreneurs congolais qui font confiance à Meeteka pour leur croissance et leur transformation digitale.",
    "about.callToAction.button.label": "Commencez Maintenant",

    "services.simplification-administrative.slug": "simplification-administrative",
    "services.callToAction": "En savoir plus",
    "services.simplification-administrative.title": "Simplification Administrative",
    "services.simplification-administrative.description": "Nous facilitons vos démarches administratives pour vous permettre de vous concentrer sur votre cœur de métier.",
    "services.simplification-administrative.accompagnement-dans-les-procédures-légales": "Accompagnement dans les procédures légales",
    "services.simplification-administrative.optimisation-des-processus-administratifs": "Optimisation des processus administratifs",
    "services.simplification-administrative.gestion-documentaire-simplifiée": "Gestion documentaire simplifiée",

    "services.information-fiscale.slug": "information-fiscale",
    "services.information-fiscale.title": "Information Fiscale",
    "services.information-fiscale.description": "Accédez à toutes les informations essentielles sur la fiscalité et les incitations disponibles en RDC.",
    "services.information-fiscale.veille-fiscale-personnalisée": "Veille fiscale personnalisée",
    "services.information-fiscale.guide-des-incitations-fiscales": "Guide des incitations fiscales",
    "services.information-fiscale.conseil-en-optimisation-fiscale": "Conseil en optimisation fiscale",

    "services.acces-financements.slug": "acces-financements",
    "services.acces-financements.title": "Accès aux Financements",
    "services.acces-financements.description": "Nous vous accompagnons dans la recherche et la sécurisation de financements adaptés à vos besoins.",
    "services.acces-financements.mise-en-relation-avec-les-investisseurs": "Mise en relation avec les investisseurs",
    "services.acces-financements.préparation-des-dossiers-de-financement": "Préparation des dossiers de financement",
    "services.acces-financements.négociation-des-conditions": "Négociation des conditions",

    "services.formation-continue.slug": "formation-continue",
    "services.formation-continue.title": "Formation Continue",
    "services.formation-continue.description": "Développez les compétences de votre équipe grâce à nos programmes de formation sur mesure.",
    "services.formation-continue.formations-managériales": "Formations managériales",
    "services.formation-continue.ateliers-pratiques": "Ateliers pratiques",
    "services.formation-continue.coaching-personnalisé": "Coaching personnalisé",

    "services.accompagnement-strategique.slug": "accompagnement-strategique",
    "services.accompagnement-strategique.title": "Accompagnement Stratégique",
    "services.accompagnement-strategique.description": `Bénéficiez d'un suivi personnalisé pour optimiser votre croissance et votre développement.`,
    "services.accompagnement-strategique.analyse-de-marché": "Analyse de marché",
    "services.accompagnement-strategique.planification-stratégique": "Planification stratégique",
    "services.accompagnement-strategique.suivi-des-performances": "Suivi des performances",

    "services.stabilite-securite.slug": "stabilite-securite",
    "services.stabilite-securite.title": "Stabilité & Sécurité",
    "services.stabilite-securite.description": `Nous vous aidons à naviguer dans l'environnement économique congolais en toute sécurité.`,
    "services.stabilite-securite.gestion-des-risques": "Gestion des risques",
    "services.stabilite-securite.conformité-réglementaire": "Conformité réglementaire",
    "services.stabilite-securite.protection-des-intérêts": "Protection des intérêts",

    "success-stories.title": "Histoires à succès",
    "success-stories.description": "Célébrer les réalisations des entrepreneurs congolais",
    "success-stories.more": "Lire l'histoire d'un succès",

    "success-stories.banner.title": "Histoires à succès",
    "success-stories.banner.description": " Découvrez comment nous avons aidé des entreprises congolaises à atteindre leurs objectifs et à transformer leurs ambitions en succès.",
    "success-stories.button.more": "Voir les détails",

    "partners.banner.title": "Nos Partenaires",
    "partners.banner.description": "Découvrez notre réseau d'experts et de professionnels dédiés à votre réussite.",
    "partners.button.more": "Voir les détails",

    "organisations.banner.title": "Nos Organisations",
    "organisations.banner.description": "Découvrez notre réseau d'experts et de professionnels dédiés à votre réussite.",
    "organisations.button.more": "Voir les détails",

    "events.banner.title": "Nos Evenements",
    "events.banner.description": "Découvrez notre réseau d'experts et de professionnels dédiés à votre réussite.",
    "events.button.more": "Voir les détails",

    "entreprises.banner.title": "Nos Entreprises",
    "entreprises.banner.description": "Découvrez notre réseau d'experts et de professionnels dédiés à votre réussite.",
    "entreprises.button.more": "Voir les détails",

    "pricings.banner.title": "Nos tarifs",
    "pricings.banner.description": "Des solutions adaptées à chaque étape de votre croissance. Choisissez le plan qui correspond le mieux à vos besoins.",
    "pricings.callToAction.title": "Des questions ?",
    "pricings.callToAction.description": "Notre équipe est là pour vous aider à choisir la meilleure solution.",
    "pricings.callToAction.button.label": "Contactez-nous",

    "diffusions.title": "Dernières Diffusions",
    "diffusions.description": "Conseils d'experts et stratégies pour votre succès digital",
    "diffusions.more": "Voir toutes les diffusions",
    "diffusions.banner.title": "Nos Diffusions",
    "diffusions.banner.description": "Découvrez nos guides et ressources pour développer votre entreprise et réussir dans l'économie digitale.",

    "missions.title": "Dernières Missions",
    "missions.description": "Conseils d'experts et stratégies pour votre succès digital",
    "missions.more": "Voir toutes les missions",
    "missions.banner.title": "Nos Missions",
    "missions.banner.description": "Découvrez nos guides et ressources pour développer votre entreprise et réussir dans l'économie digitale.",

    "blogs.title": "Dernièrs Blogs",
    "blogs.description": "Conseils d'experts et stratégies pour votre succès digital",
    "blogs.more": "Voir tout les blogs",
    "blogs.banner.title": "Nos Blogs",
    "blogs.banner.description": "Découvrez nos guides et ressources pour développer votre entreprise et réussir dans l'économie digitale.",

    "teams.title": "Notre Équipe",
    "teams.description": "Les experts derrière votre succès digital",

    "customers.title": "Avis des clients",
    "customers.description": "Ce que nos clients disent de leur collaboration avec nous",

    "contact.title": "Parlons-en",
    "contact.description": "Prêt à entamer votre voyage numérique ? Prenez contact avec nous dès aujourd'hui.",
    "contact.email": "Email",
    "contact.phone": "Téléphone",
    "contact.address": "Adresse",
    "contact.name": "Nom",
    "contact.name.placeholder": "John Doe",
    "contact.message": "Message",
    "contact.message.placeholder": "Parlez-nous de votre projet...",
    "contact.button.send": "Envoyer un message",

    "footer.description": "Votre partenaire de confiance pour l'excellence du marketing numérique.",
    "footer.right": "Tous droits réservés.",
    "footer.section.follow": "Suivez-nous",
    "footer.section.contact": "Contact",
    "footer.section.links": "Liens utiles",
    "footer.section.links.services": "Services",
    "footer.section.links.success-stories": "Histoires à succés",
    "footer.section.links.diffusions": "Diffusions",
    "footer.section.links.organisations": "Organisations",
    "footer.section.links.missions": "Missions",
    "footer.section.links.entreprises": "Entreprises"

}
export default fr